
- name: "Build SNST kali"
  hosts: localhost
  connection: local
  tasks:
    - name: "Demo debug"
      debug:
        msg: "Testing this ansible playbook"
  roles:
    - role: "roles/configure-tmux"
    - role: "roles/customize-terminal"
    - role: "roles/install-tools"
    - role: gantsign.visual-studio-code
      users:
        - username: "{{ ansible_user_id }}"
          visual_studio_code_extensions:
            - streetsidesoftware.code-spell-checker
            - ms-python.python
            - snyk-security.snyk-vulnerability-scanner
