
- name: "Build SNST kali"
  hosts: localhost
  connection: local
  tasks:
    - name: "Demo debug"
      debug:
        msg: "Testing this ansible playbook"
  roles:
    - role: "roles/configure-tmux"
    - role: "roles/customize-terminal"
    - role: "roles/install-tools"
