- name: "Download obsidian app installer iamge"
  get_url:
    url: "https://github.com/obsidianmd/obsidian-releases/releases/download/v1.5.12/Obsidian-1.5.12-arm64.AppImage"
    dest: "/tmp/obsidian.AppImage"
    mode: 0777
- name: "installing obsidian app installer"
  shell: |
    cd /tmp
    ./obsidian.AppImage
