
- name: "Install go"
  apt:
    name: golang-go
    state: present
  become: true
  become_method: sudo
- name: "Cloing kerbrute github repo"
  git:
    repo: "https://github.com/ropnop/kerbrute"
    dest: "/tmp/kerbrute"
- name: "building kerbrute"
  shell: |
    cd /tmp/kerbrute
    go build
- name: "Move Kerbrute"
  copy:
    src: "/tmp/kerbrute/kerbrute"
    dest: "{{ansible_env.HOME}}/.local/bin/"
    mode: 0744
